### ISSUE TITLE
Https on demo.sylius.org

### ISSUE THREAD

**Issue by OndraM** [Sylius/SyliusDemo#14]
Hi,
first of all, thanks for providing the demo app! Its great to have possibility to see Sylius in action without installation. 

However I come across an issue with the https, which is not present on the http://demo.sylius.org, making browsers to complain about insecure site, and eg. Firefox is showing big warning near the password field on login and registration (https://support.mozilla.org/en-US/kb/insecure-password-warning-firefox).

I understand it may not always be easy to switch to https, but this could make a bad first impression :-/. So switch to https would be great! :)

**Comment by pamil** [comment]
It looks like it is already working at https://demo.sylius.org, we just need to change demo links on our website and in docs.
