### ISSUE TITLE
Database not created with fresh platform.sh install

### ISSUE THREAD

**Issue by OndraM** [Sylius/SyliusDemo#15]
Hi, I tried to install the Demo app using platform.sh to my own environment.

However using the default `.platform.app.yml` it does not work, because the deploy hook does not create new database (it only applies fixtures).

The errors in deploy log are like:
```
 [Doctrine\DBAL\Exception\TableNotFoundException]                                                                                                            
  An exception occurred while executing 'DELETE FROM sylius_channel_currencie  
  s':                                                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'main.sylius_chan  
  nel_currencies' doesn't exist    
                                                                               
  [Doctrine\DBAL\Driver\PDOException]                                          
  SQLSTATE[42S02]: Base table or view not found: 1146 Table 'main.sylius_chan  
  nel_currencies' doesn't exist                                                
...
```

and the app won't start because of Doctrine error (ale the tables in the db are basically missing).

I fixed it by adding `php bin/console --env=prod sylius:install:database` to the deploy hook; but I'm not a platform.sh expert and the log was still full of some errors, so maybe there is also some other underlying problem.

**Comment by lchrusciel** [comment]
Unfortunately, this is how platform.sh works. At the first time, you need to set up a database. There is no significant gain to set up a failsafe script to determine if the database should be created. You can do it once and forget about it if you check `pull_requests_clone_parent_data` option to true.
