### ISSUE TITLE
Problem when installing Sylius

### ISSUE THREAD

**Issue by bouminjil** [Sylius/SyliusDemo#34]
Problem  league/uri-components  requirment during install sylius 

Problem 1
    - Installation request for league/uri-components 1.8.0 -> satisfiable by league/uri-components[1.8.0].
    - league/uri-components 1.8.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 2
    - Installation request for sylius/sylius v1.1.2 -> satisfiable by sylius/sylius[v1.1.2].
    - sylius/sylius v1.1.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
  Problem 3
    - Installation request for instaclick/php-webdriver 1.4.5 -> satisfiable by instaclick/php-webdriver[1.4.5].
    - instaclick/php-webdriver 1.4.5 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 4
    - Installation request for stripe/stripe-php v4.13.0 -> satisfiable by stripe/stripe-php[v4.13.0].
    - stripe/stripe-php v4.13.0 requires ext-curl * -> the requested PHP extension curl is missing from your system.
  Problem 5
    - sylius/sylius v1.1.2 requires ext-gd * -> the requested PHP extension gd is missing from your system.
    - friendsofphp/php-cs-fixer v2.8.4 requires symfony/polyfill-php70 ^1.0 -> satisfiable by sylius/sylius[v1.1.2].
    - Installation request for friendsofphp/php-cs-fixer v2.8.4 -> satisfiable by friendsofphp/php-cs-fixer[v2.8.4]

**Comment by Zales0123** [comment]
Hello @bouminjil, as messages explains, you're missing some extensions for the php (`curl` and `gd`). You should install them as they are apparently required by some library. Btw, I don't know how you install Sylius on your local machine, but as you've opened this issue in **SyliusDemo** repository, I want to remind you to take a look at our installation guide (http://docs.sylius.com/en/1.1/book/installation/index.html) - you should use **SyliusStandard** or **Sylius** itself :)
