### ISSUE TITLE
Online Syliusdemo doesn't work

### ISSUE THREAD

**Issue by daifabde** [Sylius/SyliusDemo#5]
Hello;
I don't know where to report this issue.
But the online demo of sylius  (http://demo.sylius.org) doesn't work.

`Fatal error: Uncaught PDOException: SQLSTATE[HY000] [2002] Connection refused in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php:43 Stack trace: #0 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOConnection.php(43): PDO->__construct('mysql:host=127....', 'root', NULL, Array) #1 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/PDOMySql/Driver.php(41): Doctrine\DBAL\Driver\PDOConnection->__construct('mysql:host=127....', 'root', NULL, Array) #2 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(360): Doctrine\DBAL\Driver\PDOMySql\Driver->connect(Array, 'root', NULL, Array) #3 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(429): Doctrine\DBAL\Connection->connect() #4 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(389): Doctrine\DBAL\Connection->getDatabasePlatformVersion() #5 /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Connection.php(328): Doctrine\DBAL\Connection->detectDatabasePlatform() #6 /app/vendor/doctrine/orm/lib/Doctrine/ORM/Mapping/ClassMetadataFactory.ph in /app/vendor/doctrine/dbal/lib/Doctrine/DBAL/Driver/AbstractMySQLDriver.php on line 103`

**Comment by michalmarcinkowski** [comment]
That is correct place for reporting all demo related issues. We're in the middle of maintenance work and we're aware of the problem, but thanks for reporting anyway 😉  We will make it work ASAP.

**Comment by daifabde** [comment]
Ok @michalmarcinkowski thanks for your answer :smile:

**Comment by pjedrzejewski** [comment]
I have reverted it to previous version, hopefully I have another go at deploying the new one. :)
